### ISSUE TITLE
LCG is 100x faster when running pytorch models

### ISSUE THREAD

**Issue by patrickbryant** [CoffeaTeam/lpcjobqueue#17]
For some reason when I use LCG_102 which has pytorch and coffea, my pytorch model runs at about 200 events/second. If I run the exact same test using the coffea-dask image in singularity, I get ~2 events/second. This speeds up to about 100 events/second if I set `executor_args['workers']=1`. Unfortunately there is nothing I have been able to do to replicate anything close to this performance when using LPCCondorCluster even when I set `cluster_args['cores']=1` and `cluster.adapt(minimum=1, maximum=1)`. 

Pytorch is officially supported by Dask but... it seems like the dask/pytorch threading is somehow causing a bottleneck where the CPU is getting absolutely thrashed moving things around but almost nothing gets done.

**Comment by patrickbryant** [comment]
Maybe related to this: https://blog.dask.org/2018/07/23/protocols-pickle

**Comment by patrickbryant** [comment]
the coffea-dask image has pytorch 1.7.1 while LCG_102 has 1.11.0.

**Comment by lgray** [comment]
The versioning probably has to do with pinned versions of python and dask. I can see if we can make an image with more recent pytorch, but probably hard given all the constraints we have to follow for a working receipe.

I would suggest converting your model to onnx at this point.

**Comment by patrickbryant** [comment]
I actually think I have a hint of what's going on. I k-fold my models, evaluating three different models, one for every third event. It seems like this results in the models being applied to non-contiguous memory blocks that dask doesn't like

**Comment by lgray** [comment]
Oh are you using a dask dataframe or something to feed a pytorch model? Or are you reading things in via uproot as in a typical coffea processor? You're not saying enough about what you are actually doing for me to have a good understanding of your real problem. It could be that dask just manages torch poorly for given versions. That or torch is trying to spin up too many threads.

You may want to try forcing `torch.set_num_threads(1)` within your processor so it doesn't clobber whatever node it lands on.

**Comment by patrickbryant** [comment]
Good idea but that didn't fix it :(

I'm trying to recreate the issue with a simple example but so far I've been unsuccessful

**Comment by patrickbryant** [comment]
Ok part of the confusion is being caused by the chunksize being ignored when using dask_executor. I've submitted a bug here: https://github.com/CoffeaTeam/coffea/issues/726

This made it seem like the job was taking far longer than it should but actually it was just doing far more work than I wanted for my tests on condor. I am now able to get about ~110 events/second on condor, it just took 14 minutes to run the test because it was doing all 98k events in my test file instead of only `chunksize=100`.

**Comment by nsmith-** [comment]
I think this is solved now that the new chunking is implemented
