### ISSUE TITLE
Implement a variation for lxplus

### ISSUE THREAD

**Issue by nsmith-** [CoffeaTeam/lpcjobqueue#2]
Despite the repo's name, we can probably generalize the code to be useful on lxplus as well. I am not sure what limitations lxplus has, but I assume there are enough that the dask-jobqueue `HTCondorCluster` is not viable by itself? @maxgalli may be interested.

**Comment by nsmith-** [comment]
Pinging also @andrzejnovak I think there is a restricted set of ports open between the worker and lxplus login nodes currently.

**Comment by andrzejnovak** [comment]
I've planned to go back to that. From my first look, it seems like it should be a bit easier since the filesystems are less restricted than lpc at least

**Comment by maxgalli** [comment]
Hi, thanks for the ping. Apparently lxplus wasn't properly configured to have Dask running on it until a few months ago. 
I opened a ticket for it and they configured it, but there are indeed some restrictions for what concerns the ports to use for workers and nannies. 
You can probably find these two links useful:
1. [Service desk ticket](https://cern.service-now.com/service-portal?id=ticket&table=u_request_fulfillment&n=RQF1699933)
2. [JIRA ticket](https://its.cern.ch/jira/browse/BBC-2828)

The second in particular contains a minimal reproducer of how I had to configure the ```HTCondorCluster``` to run a small example on lxplus.

**Comment by andrzejnovak** [comment]
Ah perfect, it's your ticket that I was going off on my last try. :) What wasn't clear to me from the ticket is, did you start the scheduler separately somehow or is the "script" bit runnable by itself.

**Comment by maxgalli** [comment]
I think that what Ben summarizes in the JIRA ticket are two different attempts that we managed to make work and that I reported (in a quite confusing way :)) in the Service Desk ticket.
To make it more clear:

- the script is standalone; it sets up a cluster (with no nannies for the workers), connects a client, submits a lambda and gets the result;
- the part above
```
lxplus7106.cern.ch: dask-scheduler --host lxplus7106.cern.ch --port 8786
lxplus742.cern.ch: dask-worker --host lxplus742.cern.ch lxplus7106.cern.ch:8786 --nthreads 1 --memory-limit 300.00MB --name workssss --nanny --nanny-port 8785 --worker-port 8786
```
is the alternative way of setting up schedulers and workers, and I use also nannies in this case (the port was suggested by Ben); but if I remember correctly for this second case I only checked that they established the communication, without trying try to submit actual work.

**Comment by nsmith-** [comment]
At the FNAL LPC we have a restricted port range (`10000:10100`) to play with, and this library sets up workers and nannies on a subset of those ports. Because of the GIL it really isn't ideal to have single workers with large thread counts, so having just one or two ports per worker to play with is rather debilitating unless you are lucky or somehow arrange in the job requirements to get one slot per machine.

**Comment by maxgalli** [comment]
Hi, Ben has [updated the documentation](https://batchdocs.web.cern.ch/specialpayload/dask.html) and enabled the range of ports 10000:10100 for the workers on LXPlus as well.

I can start working on the implementation of a similar structure (i.e. something like ```LXPlusCondorJob``` and ```LXPlusCondorCluster```) for lxplus to contribute to this package, if this exercise hasn't already been started by someone else.

Are there any indications in this sense?

**Comment by andrzejnovak** [comment]
@maxgalli It's nice to see the port range got extended (cc @lgray who asked about it recently) I've been able to work with the example and get coffea scaling out with the regular `dask_jobqueue.HTCondorCluster` You can see the implementation [here](https://github.com/cms-btv-pog/BTVNanoCommissioning/blob/master/runner.py#L275) Maybe the hardcoded port can now be fixed to the extended range instead

**Comment by maxgalli** [comment]
@andrzejnovak thanks for sharing! 

Also my jobs take quite a while to be scheduled. Initially I thought it was a matter of priority, but maybe it's worth dig deeper into it.

**Comment by bendylan** [comment]
Happy to help with the scheduling issues, we're keen to help get these kinds of use cases supported. Feel free to reach out directly via mail though for the details - not sure this GH issue is necessarily the best place to start writing about job IDs, accounting groups and scheduling priorities.

**Comment by nsmith-** [comment]
Looks like this is now available in https://github.com/cernops/dask-lxplus

**Comment by lgray** [comment]
@nsmith- we should put a link in our readme!

**Comment by nsmith-** [comment]
oops we both did, can't hurt :)
