### ISSUE TITLE
`RuntimeError: Condor configuration  not found!` with the newest release

### ISSUE THREAD

**Issue by ikrommyd** [CoffeaTeam/lpcjobqueue#39]
If you start from scratch by `curl`ing and `bootstrap`ing, then you will run into this
```
RuntimeError: Condor configuration  not found!
Please download and run bootstrap.sh again to update the shell with:
curl -OL https://raw.githubusercontent.com/CoffeaTeam/lpcjobqueue/main/bootstrap.sh; bash bootstrap.sh
```
which will appear in the logs.
Potentially a side effect of https://github.com/CoffeaTeam/lpcjobqueue/pull/36 and this is the only recent change I see
To reproduce run any computation like:
```
from distributed import Client
from lpcjobqueue import LPCCondorCluster
import logging


logging.basicConfig(level=logging.DEBUG)

cluster = cluster = LPCCondorCluster(job_script_prologue=["export LD_LIBRARY_PATH=/usr/local/lib:$LD_LIBRARY_PATH"], log_directory="/uscms/home/ikrommyd/dask_logs", ship_env=True)
cluster.adapt(minimum=0, maximum=10)
client = Client(cluster)

for future in client.map(lambda x: x * 5, range(10)):
    print(future.result())
cluster.close()
```

PS `job_script_prologue=["export LD_LIBRARY_PATH=/usr/local/lib:$LD_LIBRARY_PATH"]` is necessary if you wanna use the latest `coffea 2024.11.0` images.

**Comment by ikrommyd** [comment]
cc @kpedro88

**Comment by kpedro88** [comment]
Can't reproduce. The environment variable is set here: https://github.com/CoffeaTeam/lpcjobqueue/blob/eeb776897cea3b8ad16fc87dd8ad40a4dd78313a/bootstrap.sh#L52. The following sequence works fine for me, starting from a new lpc session:
```
curl -OL https://raw.githubusercontent.com/CoffeaTeam/lpcjobqueue/main/bootstrap.sh
bash bootstrap.sh
./shell coffeateam/coffea-base-almalinux8:latest
python -c 'from lpcjobqueue import schedd'
```

**Comment by ikrommyd** [comment]
That's not a reproducer. The variable is set on the shell, but not on the workers. You need to try a computation on the workers to see the error. Try my reproducer with `./shell coffeateam/coffea-dask-almalinux8:2024.8.1-py3.11` for example, I'm saying 2024.8.1 cause it doesn't havee any `htcondor` version issues. You will see it on the condor worker logs, not in the terminal

**Comment by ikrommyd** [comment]
https://github.com/CoffeaTeam/lpcjobqueue/pull/36/files#diff-0fb4248cb4ebb3829bc7223a712ee557f834658c0c38a562e2abbb1671996376L8-L11

This used to be warning. So what you would see is only a warning in the workers before. Now it raises an error which effectively crahes them.

**Comment by ikrommyd** [comment]
Try `curl`ing the older version `curl -OL https://raw.githubusercontent.com/CoffeaTeam/lpcjobqueue/2f4f325/bootstrap.sh` and see the difference. The warning would be there in the worker logs as the workers are not aware of this environment variable.

**Comment by kpedro88** [comment]
> The variable is set on the shell, but not on the workers.

Ah, this is the part that wasn't clear to me from the initial report.

@nsmith- do you have an opinion on how we should avoid this? (introduced in https://github.com/CoffeaTeam/lpcjobqueue/pull/36/commits/7ab78e338ca76e13a087121298a3b42b6eaffcfe)

**Comment by nsmith-** [comment]
Ah my bad, I must have skipped a round of testing before merging.
I was wondering why it was a warning considering it would mean no ability to submit jobs. But I see it is for the case where the environment is shipped to workers and this module ends up imported. Best would be to detect worker vs. client, but the quick solution is probably just to go back to a warning.
